### ISSUE TITLE
jQuery replacement method

### ISSUE THREAD

**Issue by Codelica** [SU-SWS/open_framework#108]
Hello,

I think some of the JS related issues popping up may be due to the current replacement method for core jQuery (in open_framework_preprocess_page() ).  This doesn't actually replace core's library in the output, it just adds OFW's jQuery package later in the list. (The unset() call doesn't actually unset core's version)  With both scripts in place, trouble can pop up randomly.

While I believe hook_library_alter() is the "best" way to do the swap, I don't think themes can use the call.  The think the next best method is hook_js_alter():

http://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_js_alter/7

I'm using this successfully in my branch.  Here is the relevant commit:

https://github.com/Codelica/open_framework/commit/b40e4f45212f616344a6b61fa6b9d819fdcc3b8d

This will replace core's jQuery with jQuery 1.9.1 and migrate 1.1.1 and make sure they are the first two scripts included. (1.9.1 just fixes I prefer)

One other thing to note, I'm not excluding the user or add/edit namespaces, as that's still "front end" for my sites and I want the newer jQuery there.

It's hard to say what quirks in the admin, cpanels, user, etc, may be due to the dual libraries or later loading.  Probably just have to give it a try and see. 

Thanks...

**Comment by meganem** [comment]
Thanks James! Brian and I will check it out.

**Comment by hyperboy** [comment]
Your jQuery replacement method works great!  Previously we reverted to jQuery 1.8.2 since there was a conflict with the show/hide sections when we ran both jQuery 1.4.4 and 1.9.1 concurrently.  You're right about the user and add/edit namespaces.  We excluded the new jQuery before to make the show/hide sections work on those pages.  The show/hide sections work fine when only the jQuery 1.9.1 is called.  We've incorporated your code to the main branch.  Thanks James!
