### ISSUE TITLE
Incompatability with WYSIWYG contrib module

### ISSUE THREAD

**Issue by agold2** [SU-SWS/open_framework#116]
Steps to reproduce
1. Install WYSIWYG (https://drupal.org/node/371459)
2. Edit a node and select text format that is using a WYSIWYG profile, enable rich text
3. WYSIWYG toolbar does not show up.
4. If I switch themes, e.g. to Seven, WYSIWYG works.

Thanks for the great theme. I saw https://github.com/SU-SWS/open_framework/issues/57, not sure if that's related.

**Comment by Codelica** [comment]
I don't use WYSIWYG, but this may be due to the updated jQuery (1.9.1 in Open Framework) which has doesn't have the handleError() call used in D7 core's jQuery form plugin (jquery.form.js).  I noticed this with the Image/File field widget.   Basically handleError() was removed in jQuery 1.5+ so an updated jquery form plugin is needed.  I added it via this commit if anyone wants to try it out:

https://github.com/Codelica/open_framework/commit/be220dc8420936bba19ea3cf2975ed294a5fb5cc

**Comment by agold2** [comment]
Thank you for your quick response. 

I apologize, but the issue was with the latest stable release of Open Framework. I cloned the latest dev and cannot reproduce the issue. WYSIWYG is now working.

Closing.

**Comment by jbickar** [comment]
This persists in latest 7.x-2.x (as of commit bceb9c47f6509ed18e2f174174ced2694d41b0c4)

**Comment by meganem** [comment]
We don't recommend OFW be used as an admin theme.
