### ISSUE TITLE
Undefined index: scope in drupal_get_js

### ISSUE THREAD

**Issue by jbickar** [SU-SWS/open_framework#126]
Sorry, I don't have more complete information, but I ran across this error on someone else's site. The error message is:
Undefined index: scope in drupal_get_js()

This issue https://drupal.org/node/1306584 seems to point to hook_js_alter(), so this would be openframework_js_alter() in template.php.

**Comment by meganem** [comment]
Any idea if this is urgent / not urgent?

**Comment by navster** [comment]
I came across the same error. I believe it's related to a 'jquery object not found' on jquery-migrate, In my case, removing the jQuery Update module did the trick.

**Comment by v753** [comment]
after setting subtheme 'set as default' periodically generates an error
Notice: Undefined index: scope in drupal_get_js() (line 4263 of /includes/common.inc).
p.s. 
jQuery Update 7.x-2.3+4-dev (2013-Apr-09)
Open Framework 2.04

**Comment by Codelica** [comment]
Is everyone here using jQuery Update in addition to Open Framework?  Open Framework includes jQuery 1.9.1 currently, and uses hook_js_alter() to replace core's older version.  So the jQuery Update module is not needed and is likely changing core's jQuery inclusions before Open Framework, causing a conflict. I can take a peek at what it's doing some time, or wrap it with some conditional/warning, but in the end there will probably be trouble using both a theme and a module that both try to update jQuery.

**Comment by aunymoons** [comment]
I've been getting this same mistake all over the spanish version of my site, it's related to the jquery update module. Whenever the jquery update module is turned ON, you can see how this same error appears twice at the top of the page, and whenever i try to upload an image or add anything to any field when creating a node, the image will upload but the error will appear again right above it. Now When the Jquery update module is turned OFF the error dissappears BUT! (and this is a big but) it creates a new error when uploading an image on nodes, the image will upload but the ajax will get stuck and won't give any feedback at all that the image was uploaded, nor will it show the preview of the image.
Here is my site:

http://www.sexmind.es

If anyone is interested in seeing it happen just log in with Test as username and "testie" as password (random user i created for testing purposes with enough privileges to post book pages)

http://www.sexmind.es/node/add/book is where it happens, when you try to add an image in the "imagen" section and you press the "subir al servidor" (upload to server in spanish, sorry for not being in english, its the green button ) the blue spinwheel will just keep on going forever, if you refresh the page it will show the uploaded preview of the image, but is a horrible feedback-lacking experience from the user's perspective.

I'm not sure if anybody else has the same problem but is the only bug i've had since i turned off the jquery update module. If more information is needed to see the source of the bug please let me know. i'm running latest Open Framework 7.x-2.04 release drupal 7.22 on a EC2 m1 Ubuntu instance in AWS. it's a bit urgent for me as i have a presentation of this site for friday next week.

**Comment by Codelica** [comment]
You are correct to be disabling the jQuery Update module if you are using Open Framework (which updates jQuery on its own).

I believe the image upload error you are noticing is due to Drupal core using an old version of the jQuery Form plugin , which is incompatible with jQuery 1.5+.  (Basically handleError() was removed in jQuery 1.5 which the plugin used)

It's been on my list to submit a issue on this, just no time. :(  But if the OFW committers want to consider it, they will find my commit here:

https://github.com/Codelica/open_framework/commit/be220dc8420936bba19ea3cf2975ed294a5fb5cc

-James

**Comment by chrismcandrew** [comment]
Yep, that was the problem for me. As soon as I disabled jQuery Update, good to go. Thanks.

**Comment by jmbailey** [comment]
Thank you!  This had been nagging at me for a while.  :)

**Comment by chrismcandrew** [comment]
One thing that I did narrow it down to besides the jquery module, it definitely has something to do with the sub-theme. When I added Seven back as my default admin, it corrected the error. Try changing your admin theme and even if the jquery update module is disabled, you should see the error again. Revert your admin theme and it should go away. Total pain and this is why you need to enable/disable things one at a time. Otherwise, it's so hard to pinpoint anything.

**Comment by hyperboy** [comment]
See Related ticket: https://github.com/SU-SWS/open_framework/issues/158

**Comment by tassaf85** [comment]
I am facing jQuery problem, after disabling jQuery update module the problem solved..
My question is: Is there any alternative solution, because jQuery update module should be enabled as I think

**Comment by hyperboy** [comment]
Try using the [7.x-2.05-beta](https://github.com/SU-SWS/open_framework/releases/tag/7.x-2.05-beta) release to see if it works for you.
