### ISSUE TITLE
Using Twitter Bootstrap sass version

### ISSUE THREAD

**Issue by webmasterpf** [SU-SWS/open_framework#138]
Hi

Which file is using to resize images on mobile into OFW original ? Because after replacing TB by is sass version images aren't resized like with original files,perhaps i don't finish the right HTML markup yet.

thanks

**Comment by webmasterpf** [comment]
First problem, blocks doesn't horizontally align because .clear-row doesn't exist in the sass version code and the original code,
so when i do as the doc say :

``` html
 <div class="row">
    <div class="span4">...</div>
    <div class="span8">...</div>
    </div>
```

the second elements go downside the first...
this clear-row class come from where ? did you add it ?
it seem to be and addition of OFW, so i need to port it to the sass TB version...

**Comment by webmasterpf** [comment]
Found the way, i wrote an article about that (in french) : 
http://www.graphisme-libre.info/site/2013/05/utiliser-twitter-bootstrap-sass-avec-openframework/

Additionnal question : which mechanism resize images on mobile ? it's out of the box with OFW basic sub-theme but it doesn't work on my actually modified sub-theme (TBS Sass) 

thanks

**Comment by webmasterpf** [comment]
About media-queries, do i need to make myself ? row and span couldn't move automatically with TBS and OFW ?

**Comment by meganem** [comment]
I haven't used the SASS version of TBS before, so I'm not sure how robust it is. If you use OFW out of the box, media queries, image max width and other elements should work as expected. My suggestion for troubleshooting would be to turn on/off your subtheme in order to pinpoint the issue, and then perhaps also make an alternate subtheme that does not use the SASS version of TBS. 

Bootstrap is not written in SASS by default – it uses LESS – so I can't vouch for the SASS code and whether it covers all the things the original code does.

**Comment by webmasterpf** [comment]
Media queries depend on choice of block type layout ? Like row, span,etc...the issue could be related to the miss of clear-row class in the sass version.
Fix my no resize image issue  by changing block size into em from px..
Actually the miss of clear-row class is important because rows doesn't stack themselves...
is clearfix could be an alternative ? is clear-row class come from TBS core Less code ?

**Comment by meganem** [comment]
So, the block regions behave very particular ways (responsively) due to presets we have built in to the media queries in Open Framework (see: https://openframework.stanford.edu/regions). This is a layer that is beyond what initially is in Bootstrap, so some of what you might be seeing is that your subtheme is overriding some of the Open Framework behaviors that you want to keep.

We apologize for not having a SASS version, but it's a switch that takes a shift in our workflow and institutional community culture, so we're not quite there yet.
