### ISSUE TITLE
Max-Width and other settings

### ISSUE THREAD

**Issue by ghost** [SU-SWS/open_framework#151]
Hello,
Is it possible to change settings like max-width, or font-size / line-height in a subtheme?

Thx for help

**Comment by meganem** [comment]
Hi Bernie,
The best practice here is to create a subtheme of Open Framework. We've tried to make this easy by providing the "Subtheme Kit" folder inside the theme. Copy this out and follow the instructions for naming your subtheme. In the subtheme code, you can then override the things you want to change and make your custom layer of styles. The reason to do this, instead of modifying OFW code is that when we push out updates, you will want to be able to swap out your OFW version for the new one, leaving your subtheme code untouched. Hope this is helpful.

**Comment by ghost** [comment]
Yes Megan,
I know the procedure with the subtheme.
At the moment i am looking, what files do i have to change.
OFW ist awesome.

The only thing is: I have to find out, where or in which files can i change all those things.

Thx for help

**Comment by meganem** [comment]
In the subtheme_kit folder, there is a README files with the instructions for setting up your subtheme.

**Comment by ghost** [comment]
Ok thx ...
