### ISSUE TITLE
jQuery Update errors resolution

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#158]
Brian is going to have the code check whether jQuery update is installed and let it do its thing, and then have a couple alert messages for certain situations like when people enable OFW as admin theme.

**Comment by meganem** [comment]
Related tickets:
https://github.com/SU-SWS/open_framework/issues/152
https://github.com/SU-SWS/open_framework/issues/147
https://github.com/SU-SWS/open_framework/issues/137
https://github.com/SU-SWS/open_framework/issues/126
https://github.com/SU-SWS/open_framework/issues/128

**Comment by sherakama** [comment]
This issue is not just an issue with administration themes. There are times that jquery and jquery ui are used on the front end theme. 

The solution implemented in imagex#16 ensures that OFW uses both the jquery and jquery_ui libraries that are shipped with the theme. Please review the two methods at the bottom of this file: https://github.com/kevinchampion/open_framework/blob/cf27a7d88f0ceb518ae4e8374ca4a3585ac791f9/template.php

**Comment by meganem** [comment]
Thanks!!! We'll take a look.

**Comment by hyperboy** [comment]
Regarding the jQuery Update errors, I took James' suggestion and wrapped the js_alter code with a conditional that checks if jQuery Update is installed and active. If it is then the OFW js_alter is bypassed.
