### ISSUE TITLE
Ckeditor not loading 

### ISSUE THREAD

**Issue by saptha** [SU-SWS/open_framework#173]
I tried with all the 3 recent versions of open framework (2.05, 2.04 and 2.03)
The theme is unable to load the ckeditor tool bar. I could see in the developer console that it is loading ckeditor.js but stops there.
WHenever I use any other themes like Seven the ckeditor loads properly.
What could be the issue. Can you suggest
Thanks
Saptha

**Comment by samrose** [comment]
I am able to load ckeditor in OF, so not sure what the issue you are seeing is? Try a fresh drupal install with version of ckeditor and version of OF to confirm is my suggestion

**Comment by saptha** [comment]
When I debug in chrome I can see the below two errors:
1. "Uncaught ReferenceError: jQuery is not defined"
2. "Uncaught TypeError: Object [object Object] has no method 'on' "

The first error is at the line:
/*! jQuery Migrate v1.1.1 | (c) 2005, 2013 jQuery Foundation, Inc. and other contributors | jquery.org/license */
jQuery.migrateMute===void 0&&(jQuery.migrateMute=!0),function(e,t,n){function r(n){o[n]||(o[n]=!0,e.migrateWarnings.pus

The second error is at : 
/*!
- Bootstrap.js by @fat & @mdo
- Copyright 2012 Twitter, Inc.
- http://www.apache.org/licenses/LICENSE-2.0.txt
  */
  !function(e){"use strict";e(function(){e.support.transition=function(){var e=function(){var e=document.createElement("bootstrap")

Any help is greatly appreciated. I am seeing this error both in OF version 2.04 and 2.05

**Comment by saptha** [comment]
Finally this is fixed.
When I disabled the admin_menu and tried I saw a new error this time
Notice: Undefined index: scope in drupal_get_js()
Then I updated the theme to 2.05 to accommodate the jquery update module as per the bug #158. The ckeditor appears fine now.
But still I've more work to do. The indic script module stopped working properly after this fix.
Regards
Saptha

**Comment by saptha** [comment]
Everything is working fine now. I did no more changes. 
Thanks a lot for this great theme.
Thanks
Saptha

**Comment by meganem** [comment]
Glad it's all working now!

Just an FYI, we do not recommend OFW theme be used as an administrative theme, instead use something like Seven or Rubik for editing pages and administration pages.

**Comment by shanebee** [comment]
Just a quick amendment to this closed ticket. It isn't feasible to assume that every web site will allow admin theme access to all community users (single user sites is fine, normally) and I see only frustration and late night crying sessions if you insist on bundling jQuery with OFW.

The latest 7.x-2.x-dev of jQuery Update adds an ability where admins are able to choose a jQuery version to load based on a new "default" setting. For example, administration pages can load 1.5 where the public site uses 1.8 (or 1.7, etc). This has been helpful for transitions for older sites for a variety of reasons. OFW plugging into this makes sense to me. Thus, in my humble opinion, I think Open Framework should stop using its own version of jQuery and make it a dependency that users load jQuery Update instead. (re: see late night crying sessions).

Since jQuery 2.x arrived a little while ago, we're going to have to deal with it at some point in the next 12-18 months as Drupal jumps to 8.x -- and this, of course, also applies to jQuery UI.

![2013-10-02 13_05_19-jquery update](https://f.cloud.github.com/assets/313916/1256909/2ebd0ef2-2b9e-11e3-8d97-f0c635793f21.png)

**Comment by hyperboy** [comment]
Shane, check out the latest OFW tagged release: https://github.com/SU-SWS/open_framework/releases/tag/7.x-2.05  It should now be compatible with the jQuery Update module.

**Comment by shanebee** [comment]
Rock on! Thanks, Brian!

I will give it a go. The previous patch I noted somewhere in the issue queue failed to defer to jQuery Update which prompted the previous mini-rant.
