### ISSUE TITLE
Change pager from 9 to 5!

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#212]
This is super annoying how it shows 9 pages in the pager. Not good for mobile. Change it universally to show five pages. See undergrad subtheme for pre-process function for this.

**Comment by shanebee** [comment]
Since most Drupal pagers have some connection to Drupal Views at some level, I make the submission of a little known module called Pagerer (https://drupal.org/project/pagerer)

It may contain some helpful code or, at the very least, a solution that users may want to check out rather than modifying the pager in the theme.

Of course, the module doesn't hit every single pager, I don't think.

**Comment by meganem** [comment]
I don't think we should do this by default. Let users control this.
