### ISSUE TITLE
Subtheme page.tpl.php overrides working for a flash, then not working.

### ISSUE THREAD

**Issue by nonprofitable** [SU-SWS/open_framework#221]
Created a very basic subtheme to test Open Framework for a client project. Copied page.tpl.php to the subtheme's templates folder. Switched the first sidebar to span4 instead of span3, and switched the main content to span8 instead of span9.

After clearing caches, I see the change for a brief flash on the prototype site, then it seems to rewrite to span3 somehow. Dummy text entered for testing appears as expected, so it _is_ picking up the new page.tpl.php file correctly. 

Error is viewable here: http://cpmcri.digitalraindrop.com/node

**Comment by meganem** [comment]
@hyperboy Is this something we need to document how to do? I remember it was a little more tricky than what is described above to change spans...

**Comment by nonprofitable** [comment]
I'm happy to document this if you can walk me through it (I don't write a lot of php, so this is probably my only option for contributing!). Changing the widths of a sidebar is fairly common in the Drupal world; if this is a non-standard process for Open Framework, that's a fairly big gotcha.

**Comment by nonprofitable** [comment]
Sorry; can't really hold up this project any more. I'm switching back to Omega. I'd love to give Open Framework another try in the future when the framework is documented.

**Comment by deburca** [comment]
I also created a custom sub-theme and ran into the same problem. You need to edit the override.js to match the new column spans. In my case I was able to comment out most of the over rides.

**Comment by shanebee** [comment]
Typically, I don't use the main theme for editing content as I favour Seven (and other themes like it) as I think it provides a better experience while editing content. I find that a lot of website designs can be too restrictive and prevent a lot of creative freedom if the text area is 70x20 and unable to flex. 

_Here is what I tend to do:_
1. Allow editor (or management roles) access to the Seven theme.
2. Allow community members access to the Seven theme for editing.
3. Install Display Suite module (https://drupal.org/project/ds) and turn on the form module.
4. Install Display Suite Bootstrap Layouts module (https://drupal.org/project/ds_bootstrap_layouts) and implement Bootstrap layouts on the node editing form.

I find this is a decent compromise. A note about the Display Suite Bootstrap Layouts, it does say that it requires the Bootstrap Theme. You don't need it. Since Open Framework also contains Bootstrap code, the layouts will auto-magically work.
