### ISSUE TITLE
Basic question - how to update Open Framework theme

### ISSUE THREAD

**Issue by jsibley2** [SU-SWS/open_framework#267]
I'm sure this is quite basic, but what is the recommended approach to replacing an older version of Open Framework with a newer version?

Does one have to remove the old theme first? It doesn't appear that more than one version can co-exist on a site, is that correct?

Thanks for any help!

**Comment by hyperboy** [comment]
Hi jsibley,

Here's the proper way to update the Open Framework theme:
1. Switch the theme of the site to another theme like Garland
2. Remove the open_framework directory from /sites/all/themes
3. Download the latest version of Open Framework at https://openframework.stanford.edu/downloads
4. Extract the zip file to /sites/all/themes
5. Make sure the theme directory is named "open_framework" instead of "open_framework-7.x-2.1"
6. Switch the theme of the site back to Open Framework

You can only have one version of Open Framework on a site at a time.

Brian
